version: "3.4"
services:
  centos6repo:
    volumes:
      - rpm6:/home/centos/rpmbuild/RPMS
    build:
      context: rpmbuild/createrepo
    image: rpmbuild:createrepo
    restart: always
  centos7repo:
    volumes:
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: rpmbuild/createrepo
    image: rpmbuild:createrepo
    restart: always
  webrepo:
    volumes:
      - rpm6:/home/centos-6/rpmbuild/RPMS
      - rpm7:/home/centos-7/rpmbuild/RPMS
    build:
      context: rpmbuild/webrepo
    image: rpmbuild:webrepo
    ports:
      - "80:80"
  centos6ap24build:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm6:/home/centos/rpmbuild/RPMS
    build:
      context: .
    image: rpmbuild:6-ap24build
  centos7ap24build:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      dockerfile: Dockerfile.el7
    image: rpmbuild:7-ap24build

volumes:
  rpms:
    name: rpms
  rpm6:
    name: rpm6
  rpm7:
    name: rpm7
